### ISSUE TITLE
Sync fails since update to 28.

### ISSUE THREAD

**Issue by RobertZenz** [MoonchildProductions/UXP#728]
Sync stopped working for me with a self-hosted server since I've updated to 28.

~~~
1535061644354	Sync.LogManager	DEBUG	Flushing file log
1535061644358	Sync.Status	DEBUG	Status.service: error.login.failed => success.status_ok
1535061644364	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535061644364	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535061644382	Sync.LogManager	DEBUG	Log cleanup threshold time: 1534197644382
1535061644424	Sync.LogManager	DEBUG	Done deleting files.
1535061644608	Sync.Engine.Greasemonkey	DEBUG	Engine initialized
1535061648270	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535061648270	Sync.SyncScheduler	DEBUG	Next sync in 86395730 ms.
1535061649668	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535061659666	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1535061706472	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535061706474	Sync.ErrorHandler	DEBUG	Beginning user-triggered sync.
1535061706474	Sync.Service	DEBUG	User-Agent: Pale Moon/28.0.0 (Linux x86_64) FxSync/1.54.1.20180820194930.desktop
1535061706474	Sync.Service	INFO	Starting sync at 2018-08-24 00:01:46
1535061706476	Sync.Service	DEBUG	In sync: should login.
1535061706476	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535061706476	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535061706476	Sync.Service	INFO	Logging in the user.
1535061706480	Sync.Service	DEBUG	Caching URLs under storage user base: https://mysyncserver/index.php/1.1/hjoeej4jstrcnc273vc2634vziya7igl/
1535061706482	Sync.Service	INFO	User logged in successfully - verifying login.
1535061706482	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1535061706490	Sync.Resource	WARN	GET request to https://mysyncserver/index.php/1.1/hjoeej4jstrcnc273vc2634vziya7igl/info/collections failed: [Exception... "NS_ERROR_CONNECTION_REFUSED"  nsresult: "0x804b000d (NS_ERROR_CONNECTION_REFUSED)"  location: "JS frame :: resource://services-sync/resource.js :: Channel_onStopRequest :: line 510"  data: no] Stack trace: Channel_onStopRequest()@resource://services-sync/resource.js:510 < waitForSyncCallback()@resource://services-common/async.js:98 < Res__request()@resource://services-sync/resource.js:386 < Res_get()@resource://services-sync/resource.js:415 < verifyLogin()@resource://gre/modules/services-sync/service.js:719 < onNotify()@resource://gre/modules/services-sync/service.js:1003 < WrappedNotify()@resource://services-sync/util.js:166 < WrappedLock()@resource://services-sync/util.js:121 < WrappedCatch()@resource://services-sync/util.js:95 < login()@resource://gre/modules/services-sync/service.js:1014 < sync/<()@resource://gre/modules/services-sync/service.js:1304 < WrappedCatch()@resource://services-sync/util.js:95 < sync()@resource://gre/modules/services-sync/service.js:1300
1535061706496	Sync.Service	DEBUG	verifyLogin failed: Error: NS_ERROR_CONNECTION_REFUSED (resource://services-sync/resource.js:395:19) JS Stack trace: waitForSyncCallback@async.js:98:7 < Res__request@resource.js:386:14 < Res_get@resource.js:415:12 < verifyLogin@service.js:719:18 < onNotify@service.js:1003:12 < WrappedNotify@util.js:166:21 < WrappedLock@util.js:121:16 < WrappedCatch@util.js:95:16 < login@service.js:1014:12 < sync/<@service.js:1304:14 < WrappedCatch@util.js:95:16 < sync@service.js:1300:5 < Res_get@resource.js:415:12 < verifyLogin@service.js:719:18 < onNotify@service.js:1003:12 < WrappedNotify@util.js:166:21 < WrappedLock@util.js:121:16 < WrappedCatch@util.js:95:16 < login@service.js:1014:12 < sync/<@service.js:1304:14 < WrappedCatch@util.js:95:16 < sync@service.js:1300:5
1535061706496	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1535061706496	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1535061706496	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1535061706498	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1535061706498	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1535061706498	Sync.SyncScheduler	DEBUG	Next sync in 86400000 ms.
1535061706498	Sync.ErrorHandler	ERROR	Sync encountered a login error
1535061706500	Sync.Service	DEBUG	Exception calling WrappedLock: Login failed: error.login.reason.network
1535061706500	Sync.Service	DEBUG	Not syncing: login returned false.
1535061706510	Sync.ErrorHandler	DEBUG	Addons installed: 16
1535061706510	Sync.ErrorHandler	DEBUG	 - Werewolf, version 1.0, id werewolf@bonsaimind.org
1535061706510	Sync.ErrorHandler	DEBUG	 - uBlock Origin, version 1.14.24, id uBlock0@raymondhill.net
1535061706510	Sync.ErrorHandler	DEBUG	 - Cleanest Addon Manager, version 7.1, id cam@sdrocking.com
1535061706510	Sync.ErrorHandler	DEBUG	 - InspectorWidget, version 4.38.20150523.1-signed.1-signed, id {c671b520-abe9-11d8-8ebc-000c6e787bf7}
1535061706512	Sync.ErrorHandler	DEBUG	 - DownThemAll!, version 3.0.8, id {DDC359D1-844A-42a7-9AA1-88A850A938A8}
1535061706512	Sync.ErrorHandler	DEBUG	 - Grab and Drag, version 3.2.9.9.1, id {477c4c36-24eb-11da-94d4-00e08161165f}
1535061706512	Sync.ErrorHandler	DEBUG	 - Stylish, version 2.1.1, id {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
1535061706512	Sync.ErrorHandler	DEBUG	 - Unhide Passwords, version 1.2.7.0, id {2e17e2b2-b8d4-4a67-8d7b-fafa6cc9d1d0}
1535061706512	Sync.ErrorHandler	DEBUG	 - DOM Inspector, version 2.0.16.1-signed, id inspector@mozilla.org
1535061706512	Sync.ErrorHandler	DEBUG	 - Pale Moon Commander, version 2.0.2, id commander@palemoon.org
1535061706514	Sync.ErrorHandler	DEBUG	 - Classic Password Editor, version 1.0.3, id classicpasswordeditor@daniel.dawson
1535061706514	Sync.ErrorHandler	DEBUG	 - Add-ons Manager Context Menu, version 0.4.2.1-signed.1-signed, id amcontextmenu@loucypher
1535061706514	Sync.ErrorHandler	DEBUG	 - Extended Statusbar, version 2.0.5, id {daf44bf7-a45e-4450-979c-91cf07434c3d}
1535061706514	Sync.ErrorHandler	DEBUG	 - Greasemonkey for Pale Moon, version 3.31.4, id greasemonkeyforpm@janekptacijarabaci
1535061706516	Sync.ErrorHandler	DEBUG	 - Tile Tabs, version 14[.12](url), id tiletabs@DW-dev
1535061706516	Sync.ErrorHandler	DEBUG	 - Expose Noisy Tabs, version 1.1.0, id expose-noisy-tabs@wsdfhjxc
~~~

The address of the my sync server is incorrect in these logs, though. The log gives it as `https://mysyncserver/index.php/1.1/` however, there should be a port appended to the address `https://mysyncserver:666/index.php/1.1/`, but I'm not sure whether that is the problem or not. The setting `services.sync.serverURL` is still listing the address correctly with port.

The server hasn't been touch in a half year and I've tried without extensions, no luck. This is with Pale Moon 28.0.0 under Linux.

**Comment by wolfbeast** [comment]
To narrow this down, can you run mysyncserver on port 443 to test? If that connects then we know it's a behavior change in the platform sync client no longer honoring ports.

**Comment by wolfbeast** [comment]
Actually, there's a known change in behavior in that it will use the URL the server returns - can you double-check if your server configuration to make sure the URL returned includes the port number?

**Comment by RobertZenz** [comment]
My `settings.php` contains

    define("FSYNCMS_ROOT", "https://mysyncserver:666/index.php/");

I'll conduct the other test in the evening or tomorrow and will let you know.

 > Actually, there's a known change in behavior in that it will use the URL the server returns...

Well, that's unfortunate for me. Because one of my clients is in the same network as the sync server and one is not. The problem is that I can't connect to my own IP from within my network because...well, I don't know, but seems like my ISP is not supporting that. So one client is configured to access it with the local network IP, and one through a domain. If the clients now use the returned server address, I'll have to built a workaround for that because the clients must use different addresses. Should be easy enough, though, a simple `if` in the `settings.php` should suffice I guess. Or I configure a local alias for the domain...fuel for thought.

**Comment by wolfbeast** [comment]
No that's not what I meant :)
If your FSYNCMS_ROOT is set to include the port, then that should be fine.

I do think this is a possible side-effect of what Mozilla has done to the client to cater to FxA, but I haven't been able to pinpoint exactly where the port gets stripped. ClusterURL gets stored in a different way now so it has to be somewhere in `cluster.js` or similar.

**Comment by RobertZenz** [comment]
I can confirm that it works again when I reconfigure the server to 443, so te port is being stripped from the address.

**Comment by wolfbeast** [comment]
OK, thanks for confirming.

If you unlink the browser from your account, then re-link it, the debug log should provide more information what exactly is going on with the cluster URL (which is currently stored incorrectly). You may have to enable full logging to get all the details by flipping `services.sync.log.appender.file.logOnSuccess` to capture a full trace before re-linking. I'm trying to find out where the port number is dropped on the floor but the code doesn't provide much in terms of information there so it must be a side-effect of something.

**Comment by RobertZenz** [comment]
It's already gone in that log.

~~~
1535399771572	Sync.LogManager	DEBUG	Flushing file log
1535399771586	Sync.Status	DEBUG	Status.service: error.login.failed => success.status_ok
1535399771600	Sync.LogManager	DEBUG	Log cleanup threshold time: 1534535771600
1535399771680	Sync.LogManager	DEBUG	Done deleting files.
1535399782684	Sync.Identity	INFO	Basic password being updated.
1535399782688	Sync.Identity	INFO	Sync Key being updated.
1535399782688	Sync.SyncKeyBundle	INFO	SyncKeyBundle being created.
1535399782692	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535399782692	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1535399782692	Sync.Service	INFO	Logging in the user.
1535399782694	Sync.Service	DEBUG	Caching URLs under storage user base: https://mysyncserver/index.php/1.1/user/
1535399782696	Sync.Service	INFO	User logged in successfully - verifying login.
1535399782696	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1535399782712	Sync.Resource	WARN	GET request to https://mysyncserver/index.php/1.1/user/info/collections failed: [Exception... "NS_ERROR_CONNECTION_REFUSED"  nsresult: "0x804b000d (NS_ERROR_CONNECTION_REFUSED)"  location: "JS frame :: resource://services-sync/resource.js :: Channel_onStopRequest :: line 510"  data: no] Stack trace: Channel_onStopRequest()@resource://services-sync/resource.js:510 < waitForSyncCallback()@resource://services-common/async.js:98 < Res__request()@resource://services-sync/resource.js:386 < Res_get()@resource://services-sync/resource.js:415 < verifyLogin()@resource://gre/modules/services-sync/service.js:719 < onNotify()@resource://gre/modules/services-sync/service.js:1003 < WrappedNotify()@resource://services-sync/util.js:166 < WrappedLock()@resource://services-sync/util.js:121 < WrappedCatch()@resource://services-sync/util.js:95 < login()@resource://gre/modules/services-sync/service.js:1014 < resetPassphrase()@setup.js:153 < onclick()@setup.xul:1
1535399782718	Sync.Service	DEBUG	verifyLogin failed: Error: NS_ERROR_CONNECTION_REFUSED (resource://services-sync/resource.js:395:19) JS Stack trace: waitForSyncCallback@async.js:98:7 < Res__request@resource.js:386:14 < Res_get@resource.js:415:12 < verifyLogin@service.js:719:18 < onNotify@service.js:1003:12 < WrappedNotify@util.js:166:21 < WrappedLock@util.js:121:16 < WrappedCatch@util.js:95:16 < login@service.js:1014:12 < resetPassphrase@setup.js:153:5 < onclick@setup.xul:1:1 < Res_get@resource.js:415:12 < verifyLogin@service.js:719:18 < onNotify@service.js:1003:12 < WrappedNotify@util.js:166:21 < WrappedLock@util.js:121:16 < WrappedCatch@util.js:95:16 < login@service.js:1014:12 < resetPassphrase@setup.js:153:5 < onclick@setup.xul:1:1
1535399782718	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1535399782720	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1535399782720	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1535399782720	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
1535399782720	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1535399782722	Sync.SyncScheduler	DEBUG	Next sync in 86400000 ms.
1535399782722	Sync.ErrorHandler	ERROR	Sync encountered a login error
1535399782724	Sync.Service	DEBUG	Exception calling WrappedLock: Login failed: error.login.reason.network
1535399782734	Sync.ErrorHandler	DEBUG	Addons installed: 16
1535399782736	Sync.ErrorHandler	DEBUG	 - Werewolf, version 1.0, id werewolf@bonsaimind.org
1535399782736	Sync.ErrorHandler	DEBUG	 - uBlock Origin, version 1.14.24, id uBlock0@raymondhill.net
1535399782736	Sync.ErrorHandler	DEBUG	 - Cleanest Addon Manager, version 7.1, id cam@sdrocking.com
1535399782736	Sync.ErrorHandler	DEBUG	 - InspectorWidget, version 4.38.20150523.1-signed.1-signed, id {c671b520-abe9-11d8-8ebc-000c6e787bf7}
1535399782736	Sync.ErrorHandler	DEBUG	 - DownThemAll!, version 3.0.8, id {DDC359D1-844A-42a7-9AA1-88A850A938A8}
1535399782736	Sync.ErrorHandler	DEBUG	 - Grab and Drag, version 3.2.9.9.1, id {477c4c36-24eb-11da-94d4-00e08161165f}
1535399782738	Sync.ErrorHandler	DEBUG	 - Stylish, version 2.1.1, id {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
1535399782738	Sync.ErrorHandler	DEBUG	 - Unhide Passwords, version 1.2.7.0, id {2e17e2b2-b8d4-4a67-8d7b-fafa6cc9d1d0}
1535399782738	Sync.ErrorHandler	DEBUG	 - DOM Inspector, version 2.0.16.1-signed, id inspector@mozilla.org
1535399782738	Sync.ErrorHandler	DEBUG	 - Pale Moon Commander, version 2.0.2, id commander@palemoon.org
1535399782738	Sync.ErrorHandler	DEBUG	 - Classic Password Editor, version 1.0.3, id classicpasswordeditor@daniel.dawson
1535399782740	Sync.ErrorHandler	DEBUG	 - Add-ons Manager Context Menu, version 0.4.2.1-signed.1-signed, id amcontextmenu@loucypher
1535399782740	Sync.ErrorHandler	DEBUG	 - Extended Statusbar, version 2.0.5, id {daf44bf7-a45e-4450-979c-91cf07434c3d}
1535399782740	Sync.ErrorHandler	DEBUG	 - Greasemonkey for Pale Moon, version 3.31.4, id greasemonkeyforpm@janekptacijarabaci
1535399782740	Sync.ErrorHandler	DEBUG	 - Tile Tabs, version 14.12, id tiletabs@DW-dev
1535399782740	Sync.ErrorHandler	DEBUG	 - Expose Noisy Tabs, version 1.1.0, id expose-noisy-tabs@wsdfhjxc
~~~

**Comment by RobertZenz** [comment]
Mh, there it seems to be:

~~~
...
1535400374422	Sync.Service	INFO	Logging in the user.
1535400374422	Sync.Service	INFO	User logged in successfully - verifying login.
1535400374424	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1535400374424	Sync.Service	DEBUG	Finding cluster for user robert
1535400374458	Sync.Resource	DEBUG	mesg: GET success 200 https://mysyncserver:666/index.php/user/1.0/robert/node/weave
1535400374458	Sync.Resource	DEBUG	GET success 200 https://mysyncserver:666/index.php/user/1.0/robert/node/weave
1535400374460	Sync.Service	DEBUG	Cluster value = https://mysyncserver/index.php/
1535400374460	Sync.Service	DEBUG	Setting cluster to https://mysyncserver/index.php/
1535400374460	Sync.Service	DEBUG	Caching URLs under storage user base: https://mysyncserver/index.php/1.1/robert/
1535400374474	Sync.Resource	WARN	GET request to https://mysyncserver/index.php/1.1/robert/info/collections failed: [Exception... "NS_ERROR_CONNECTION_REFUSED"  nsresult: "0x804b000d (NS_ERROR_CONNECTION_REFUSED)"  location: "JS frame :: resource://services-sync/resource.js :: Channel_onStopRequest :: line 510"  data: no] Stack trace: Channel_onStopRequest()@resource://services-sync/resource.js:510 < waitForSyncCallback()@resource://services-common/async.js:98 < Res__request()@resource://services-sync/resource.js:386 < Res_get()@resource://services-sync/resource.js:415 < verifyLogin()@resource://gre/modules/services-sync/service.js:719 < onNotify()@resource://gre/modules/services-sync/service.js:1003 < WrappedNotify()@resource://services-sync/util.js:166 < WrappedLock()@resource://services-sync/util.js:121 < WrappedCatch()@resource://services-sync/util.js:95 < login()@resource://gre/modules/services-sync/service.js:1014 < onWizardAdvance()@setup.js:488 < anonymous()@chrome://global/content/bindings/wizard.xml line 432 > Function:1 < _fireEvent()@wizard.xml:433 < advance()@wizard.xml:270 < wizard.xml:157
...
~~~

**Comment by wolfbeast** [comment]
Yup, that was what I was looking for. So it gets lost when passing the value back from resource to service. I'll have a closer look there.

**Comment by wolfbeast** [comment]
I've looked at it again but I still haven't been able to find where exactly this is dropped on the floor. It seems the uri spec is passed back through the callback function properly so it's a bit of a headscratcher, complicated by the fact that I don't have a live server on a custom port available to troubleshoot this.

**Comment by wolfbeast** [comment]
@RobertZenz I've worked on reverting the sync client to something a little more sane in terms of service integration, which lives in https://github.com/MoonchildProductions/UXP/tree/Sync-weave -- are you able to build your own from that branch or do you need me to build a binary for you to test functionality with your server?

**Comment by RobertZenz** [comment]
@wolfbeast I can try, but I'm out for the weekend and won't have much time next week, so it might take me some time. As a note, I'm using Linux, and as far as you know you are not doing the builds for that.

**Comment by wolfbeast** [comment]
Right. Well, building on Linux is a little less involved to do yourself. But maybe @trav90 has time to toss a binary your way since he has the build environment ready for it?

**Comment by trav90** [comment]
I'd be happy to provide a build for testing. I can have one ready later this afternoon.

**Comment by trav90** [comment]
@RobertZenz: https://www.dropbox.com/s/aw9yhdnjfkistoo/palemoon-28.2.0a1-sync.linux-x86_64.tar.bz2?dl=0

**Comment by RobertZenz** [comment]
@trav90 Thank you very much.

@wolfbeast I've tried it, but when I try to register a new account on my server the dialog switches to "Verifying..." and then simply states "Unknown error" with no additional information logged either in the sync logs nor in the Error Console.

I was unable to connect my current account, it failed with this:

    1540852254496	Sync.Identity	WARN	Failed to create sync key bundle: Unknown character in base32: 9

But that might be because I was updating the sync server and might have failed there. For the new account I've updated to the latest Git version, though.

**Comment by wolfbeast** [comment]
That's weird because I had no trouble creating a new account on the active server.
My main concern here though is that the custom port issue would be solved.

**Comment by RobertZenz** [comment]
Okay, I've changed my server configuration to not use custom ports for testing and this "Unknown error" also turns up with default ports. As I said, I have the latest FSyncMS from the Git repository and the test build from trav90. I've disabled SELinux on the server for testing and that doesn't help either.

Give me a few minutes, please, I'll check if I can capture the traffic between the server and Pale Moon.

**Comment by wolfbeast** [comment]
I'd like to move this forward. can anyone else verify the older client code fixes the custom port issue?

**Comment by wolfbeast** [comment]
server side issues with fsyncms can't be solved here.

**Comment by e-alfred** [comment]
I just wanted to mention that the "Unknown error" message also shows up if there is a problem on the server side just for information.

Anyway, I was able to set up an account with a custom port using Pale Moon 28.1.0 but afterwards the sync fails because the port number is not used to contact the sync server hence defaulting to standard HTTPS. Here is the error message from the log file:

```
1541803208018	Sync.Resource	WARN	GET request to https://myserver.de/index.php/1.1/c2wduqkmv7kx4pouqxinaw4px3vmv3ji/info/collections failed: [Exception... "NS_ERROR_NET_TIMEOUT"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-sync/resource.js :: Channel_onStopRequest :: line 510"  data: no] Stack trace: Channel_onStopRequest()@resource://services-sync/resource.js:510 < waitForSyncCallback()@resource://services-common/async.js:98 < Res__request()@resource://services-sync/resource.js:386 < Res_get()@resource://services-sync/resource.js:415 < verifyLogin()@resource://gre/modules/services-sync/service.js:719 < onNotify()@resource://gre/modules/services-sync/service.js:1003 < WrappedNotify()@resource://services-sync/util.js:166 < WrappedLock()@resource://services-sync/util.js:121 < WrappedCatch()@resource://services-sync/util.js:95 < login()@resource://gre/modules/services-sync/service.js:1014 < sync/<()@resource://gre/modules/services-sync/service.js:1304 < WrappedCatch()@resource://services-sync/util.js:95 < sync()@resource://gre/modules/services-sync/service.js:1300
1541803208022	Sync.Service	DEBUG	verifyLogin failed: Error: NS_ERROR_NET_TIMEOUT (resource://services-sync/resource.js:395:19) JS Stack trace: waitForSyncCallback@async.js:98:7 < Res__request@resource.js:386:14 < Res_get@resource.js:415:12 < verifyLogin@service.js:719:18 < onNotify@service.js:1003:12 < WrappedNotify@util.js:166:21 < WrappedLock@util.js:121:16 < WrappedCatch@util.js:95:16 < login@service.js:1014:12 < sync/<@service.js:1304:14 < WrappedCatch@util.js:95:16 < sync@service.js:1300:5 < Res_get@resource.js:415:12 < verifyLogin@service.js:719:18 < onNotify@service.js:1003:12 < WrappedNotify@util.js:166:21 < WrappedLock@util.js:121:16 < WrappedCatch@util.js:95:16 < login@service.js:1014:12 < sync/<@service.js:1304:14 < WrappedCatch@util.js:95:16 < sync@service.js:1300:5
1541803208024	Sync.Status	DEBUG	Status.login: error.login.reason.network => error.login.reason.network
1541803208024	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
```

**Comment by wolfbeast** [comment]
Yes, we know 28.1.0 has trouble with it :)
Can you please try with the trybuild travis posted?

**Comment by RobertZenz** [comment]
@e-alfred You should be able to access the logs by navigating to "about:sync-log" in Pale Moon.

**Comment by e-alfred** [comment]
@RobertZenz No, the release from @trav90 doesn't write any error logs into the weave folder. To confirm the problem I temporarily used a server on port 443 and it works immediately. So far the fix provided by @wolfbeast doesn't resolve the issue.

**Comment by wolfbeast** [comment]
Okay that's peculiar, then. The sync client on the test branch is exactly the same as the one on Tycho (v27). This means that the problem here lies outside of the Sync client code, which is probably why I haven't been able to pinpoint it.

Unfortunately it does mean that I have to put this on ice for the moment with a research tag; and Sync on UXP is simply not possible on non-standard ports for the time being.

**Comment by e-alfred** [comment]
@RobertZenz The problem is that Nextcloud dropped a lot of APIs  with their latest release and the Mozilla Sync app is deprecated basically (but worked pretty well until Nextcloud 13). Therefore I have to move to FSyncMS to keep the synchronization working. 

What is really odd is that I can add a new Pale Moon client to a Nextcloud instance running the mozilla_sync app running on a custom port, but not with FSyncMS.

**Comment by RobertZenz** [comment]
@e-alfred Uh, wait...could it be that this is in reality two problems:

 1. Custom ports not working in Pale Moon.
 2. Incompatibility with the latest FSyncMS.

**Comment by wolfbeast** [comment]
Hmm.. or maybe it's as simple as the fsyncms server configuration not having the port specified in its config?
Did you specify the port in settings.php for `FSYNCMS_ROOT`?

**Comment by RobertZenz** [comment]
I did.

**Comment by e-alfred** [comment]
Yes, like this:

`define("FSYNCMS_ROOT", "https://myserver.de:7324/index.php/");`

Anyway, if I use the Nextcloud Mozilla Sync app, the clusterURL is never used according to the sync log, so the custom port works well.

**Comment by FranklinDM** [comment]
The problem here might be related to FSyncMS [not including the port](https://github.com/FranklinDM/FSyncMS/commit/0df7f3c375fe910b9440b946c0da05402f2cea22) when the sync client requests for `http://*servername*:*serverport*/index.php/user/1.0/*userid*/node/weave`.
Can anyone try this copy of [FSyncMS](https://github.com/FranklinDM/FSyncMS)?

**Comment by wolfbeast** [comment]
Huh.. I'm really surprised this worked previously then.

**Comment by FranklinDM** [comment]
Pale Moon 27's sync client always assumes that the given server URL on setup is always true.

PM 28 on the other hand sends a request first to that node URL and does a few things based on its

**Comment by FranklinDM** [comment]
One can actually test this with a local xampp server through virtual hosts and by using a non-standard port.

**Comment by ibuprophen1** [comment]
Someone pointed me to the following link and I just wanted to provide it to you in hopes that it will be helpful somehow. 

https://www.davd.eu/byecloud-firefox-sync-server/


~Ibuprophen

**Comment by RobertZenz** [comment]
@FranklinDM Thanks for looking into this, I'll be testing this tomorrow with the changed sync server.

@ibuprophen1 That's got *nothing* to do with anything in here, though.

**Comment by wolfbeast** [comment]
@FranklinDM The thing is, I asked people to test with the v27 client in the tree (see above) and it still failed for them. So if it was just a matter of differences in the client that would have been solved there, but it wasn't. This is why I'm confused it worked before. The v27 client requests a cluster URL just like the v28 client, but somehow the port is retained even if FSyncMS doesn't return it; I'm guessing that must have been a bug in the URL parser in the platform that got fixed along the way, which makes both client version fail on UXP. I can't think of another reason why there would be differences here.

Waiting for @RobertZenz to check when he has time. If confirmed, I'll consider this a bug on FSyncMS to be fixed and not a bug in the client.

**Comment by FranklinDM** [comment]
@wolfbeast My assumption about the PM<27 was incorrect.
Okay, so I tried this on v27 using the current FSyncMS code and it also failed -  the port from the cluster URL is also missing:
```
...
1542629933496	Sync.UserAPI	INFO	Create account response: 200 "plmar3xnjclj3ptsyifxhsdqjl36ybv3"
1542629933497	Sync.Identity	INFO	Basic password being updated.
1542629933498	Sync.Identity	INFO	Sync Key being updated.
1542629933500	Sync.SyncKeyBundle	INFO	SyncKeyBundle being created.
1542629933508	Sync.Identity	DEBUG	Updating saved password for plmar3xnjclj3ptsyifxhsdqjl36ybv3 in Mozilla Services Password
1542629933514	Sync.Identity	DEBUG	Updating saved password for plmar3xnjclj3ptsyifxhsdqjl36ybv3 in Mozilla Services Encryption Passphrase
1542629933520	Sync.Status	DEBUG	Status.service: service.client_not_configured => success.status_ok
1542629933599	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542629933602	Sync.Tracker.History	INFO	Adding Places observer.
1542629933800	Sync.Service	DEBUG	User-Agent: Pale Moon/27.5.0 FxSync/1.40.0.20170922194459.
1542629933801	Sync.Service	INFO	Starting sync at 2018-11-19 20:18:53
1542629933801	Sync.Service	DEBUG	In sync: should login.
1542629933802	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542629933803	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542629933804	Sync.Service	INFO	Logging in the user.
1542629933836	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1542629933839	Sync.Service	DEBUG	Finding cluster for user plmar3xnjclj3ptsyifxhsdqjl36ybv3
1542629934005	Sync.Resource	DEBUG	mesg: GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/plmar3xnjclj3ptsyifxhsdqjl36ybv3/node/weave
1542629934005	Sync.Resource	DEBUG	GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/plmar3xnjclj3ptsyifxhsdqjl36ybv3/node/weave
1542629934006	Sync.Service	DEBUG	Cluster value = http://sync.franklindm.com/index.php/
1542629934006	Sync.Service	DEBUG	Setting cluster to http://sync.franklindm.com/index.php/
1542629934008	Sync.Service	DEBUG	Caching URLs under storage user base: http://sync.franklindm.com/index.php/1.1/plmar3xnjclj3ptsyifxhsdqjl36ybv3/
1542629934117	Sync.Resource	DEBUG	mesg: GET fail 404 http://sync.franklindm.com/index.php/1.1/plmar3xnjclj3ptsyifxhsdqjl36ybv3/info/collections
1542629934117	Sync.Resource	DEBUG	GET fail 404 http://sync.franklindm.com/index.php/1.1/plmar3xnjclj3ptsyifxhsdqjl36ybv3/info/collections
1542629934117	Sync.Service	DEBUG	Finding cluster for user plmar3xnjclj3ptsyifxhsdqjl36ybv3
1542629934144	Sync.Resource	DEBUG	mesg: GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/plmar3xnjclj3ptsyifxhsdqjl36ybv3/node/weave
1542629934144	Sync.Resource	DEBUG	GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/plmar3xnjclj3ptsyifxhsdqjl36ybv3/node/weave
1542629934144	Sync.Service	DEBUG	Cluster value = http://sync.franklindm.com/index.php/
1542629934144	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.account
1542629934144	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1542629934145	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
...
```
Also in v26:
```
1542630850908	Sync.Service	INFO	Loading Weave 1.26.0
1542630850911	Sync.Tracker.Clients	WARN	Changed IDs file clients contains non-object value.
1542630850912	Sync.Engine.Clients	DEBUG	Engine initialized
1542630850916	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1542630850924	Sync.Tracker.Bookmarks	WARN	Changed IDs file bookmarks contains non-object value.
1542630850925	Sync.Engine.Bookmarks	DEBUG	Engine initialized
1542630850929	Sync.Tracker.Forms	WARN	Changed IDs file forms contains non-object value.
1542630850930	Sync.Engine.Forms	DEBUG	Engine initialized
1542630850934	Sync.Tracker.History	WARN	Changed IDs file history contains non-object value.
1542630850935	Sync.Engine.History	DEBUG	Engine initialized
1542630850939	Sync.Tracker.Passwords	WARN	Changed IDs file passwords contains non-object value.
1542630850940	Sync.Engine.Passwords	DEBUG	Engine initialized
1542630850944	Sync.Engine.Prefs	DEBUG	Engine initialized
1542630850949	Sync.Engine.Tabs	DEBUG	Engine initialized
1542630850950	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1542630850958	Sync.Tracker.Addons	WARN	Changed IDs file addons contains non-object value.
1542630850959	Sync.Engine.Addons	DEBUG	Engine initialized
1542630850960	Sync.Service	INFO	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:38.9) Gecko/20100101 Goanna/2.2 Firefox/38.9 PaleMoon/26.5.0
1542630850965	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1542630850968	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.no_username
1542630850968	Sync.Status	DEBUG	Status.service: service.client_not_configured => service.client_not_configured
1542630850968	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.no_username
1542630850968	Sync.Status	DEBUG	Status.service: service.client_not_configured => service.client_not_configured
1542630851106	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.no_username
1542630851106	Sync.Status	DEBUG	Status.service: service.client_not_configured => service.client_not_configured
1542630851107	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.no_username
1542630851107	Sync.Status	DEBUG	Status.service: service.client_not_configured => service.client_not_configured
1542630873840	Sync.Identity	INFO	Username changed. Removing stored credentials.
1542630873840	Sync.Identity	INFO	Basic password has no value. Removing.
1542630873841	Sync.Identity	INFO	Sync Key has no value. Deleting.
1542630875429	Sync.UserAPI	INFO	Create account response: 200 "3tg2qvnt7u7exiznzu7ulmppkgdfzmet"
1542630875430	Sync.Identity	INFO	Basic password being updated.
1542630875431	Sync.Identity	INFO	Sync Key being updated.
1542630876765	Sync.SyncKeyBundle	INFO	SyncKeyBundle being created.
1542630876772	Sync.Identity	DEBUG	Updating saved password for 3tg2qvnt7u7exiznzu7ulmppkgdfzmet in Mozilla Services Password
1542630876963	Sync.Identity	DEBUG	Updating saved password for 3tg2qvnt7u7exiznzu7ulmppkgdfzmet in Mozilla Services Encryption Passphrase
1542630877148	Sync.Status	DEBUG	Status.service: service.client_not_configured => success.status_ok
1542630877193	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542630877193	Sync.AddonsReconciler	INFO	Registering as Add-on Manager listener.
1542630877194	Sync.AddonsReconciler	DEBUG	Adding change listener.
1542630877427	Sync.Service	DEBUG	User-Agent: Pale Moon/26.5.0 FxSync/1.26.0.20160923210021.
1542630877427	Sync.Service	INFO	Starting sync at 2018-11-19 20:34:37
1542630877427	Sync.Service	DEBUG	In sync: should login.
1542630877429	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542630877429	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1542630877429	Sync.Service	INFO	Logging in user 3tg2qvnt7u7exiznzu7ulmppkgdfzmet
1542630877429	Sync.Service	DEBUG	Finding cluster for user 3tg2qvnt7u7exiznzu7ulmppkgdfzmet
1542630877665	Sync.Resource	DEBUG	mesg: GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/3tg2qvnt7u7exiznzu7ulmppkgdfzmet/node/weave
1542630877665	Sync.Resource	DEBUG	GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/3tg2qvnt7u7exiznzu7ulmppkgdfzmet/node/weave
1542630877665	Sync.Service	DEBUG	Cluster value = http://sync.franklindm.com/index.php/
1542630877665	Sync.Service	DEBUG	Setting cluster to http://sync.franklindm.com/index.php/
1542630877667	Sync.Service	DEBUG	Caching URLs under storage user base: http://sync.franklindm.com/index.php/1.1/3tg2qvnt7u7exiznzu7ulmppkgdfzmet/
1542630877719	Sync.Resource	DEBUG	mesg: GET fail 404 http://sync.franklindm.com/index.php/1.1/3tg2qvnt7u7exiznzu7ulmppkgdfzmet/info/collections
1542630877719	Sync.Resource	DEBUG	GET fail 404 http://sync.franklindm.com/index.php/1.1/3tg2qvnt7u7exiznzu7ulmppkgdfzmet/info/collections
1542630877720	Sync.Service	DEBUG	Finding cluster for user 3tg2qvnt7u7exiznzu7ulmppkgdfzmet
1542630877800	Sync.Resource	DEBUG	mesg: GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/3tg2qvnt7u7exiznzu7ulmppkgdfzmet/node/weave
1542630877800	Sync.Resource	DEBUG	GET success 200 http://sync.franklindm.com:777/index.php/user/1.0/3tg2qvnt7u7exiznzu7ulmppkgdfzmet/node/weave
1542630877800	Sync.Service	DEBUG	Cluster value = http://sync.franklindm.com/index.php/
1542630877801	Sync.Status	DEBUG	Status.login: error.login.reason.no_username => error.login.reason.1542630877801	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1542630877801	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
```

**Comment by RobertZenz** [comment]
I was able to create a new account with the Pale Moon build provided by @wolfbeast/@trav90  and the fixes in FMSync by @FranklinDM. The sync even seems to continue to work when switching back to the default 28.2.0 as currently packaged for Ubuntu, I did not test creating a new account on that.

So from that it looks good to me so far, I will test adding a second machine tomorrow.

As a note, while skimming the FSyncMS source, I noticed that it does seem to write logs to `/tmp/`, which isn't a good place to keep logs. Ideally they would be written through the PHP logging mechanism.

**Comment by RobertZenz** [comment]
> Irrelevant as someone may want logs for sync but not the rest of php.

That is what prefixes and grep are for.

**Comment by mattatobin** [comment]
K.

**Comment by wolfbeast** [comment]
Tranferring this issue over to FSyncMS where it seems to belong.
